#!/bin/bash

# Assigns $2 version to multiseed bintary, creates stripped ('.s') version and copies it to /usr/local/bin

if [ "$#" -ne 2 ]; then
    echo "Please include version parameter ..."
else
        cp -p $1/multiseed $1/multiseed.$2
        cp -p $1/multiseed.$2 $1/multiseed.$2.s
        strip -p $1/multiseed.$2.s
        cp -p $1/multiseed.$2.s /usr/local/bin
fi
